version: '3.14'

networks:
   ms_courses:
     external: true

services:
  api.gateway:
    container_name: api.gateway
    build:
      context: .
    volumes:
      - ./build/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ms_courses
    ports:
      - '${API_GATEWAY_PORT:-5090}:5090'

